from .Medbullets_op4.Medbullets_op4 import Medbullets_op4
from .Medbullets_op5.Medbullets_op5 import Medbullets_op5
from .MedXpertQA.MedXpertQA import MedXpertQA
from .MMMU.MMMU import MMMU
from .OmniMedVQA.OmniMedVQA import OmniMedVQA
from .PATH_VQA.PATH_VQA import PATH_VQA
from .PMC_VQA.PMC_VQA import PMC_VQA
from .SLAKE.SLAKE import SLAKE
from .SuperGPQA.SuperGPQA import SuperGPQA
from .VQA_RAD.VQA_RAD import VQA_RAD
from .HealthBench.HealthBench import HealthBench
from .PubMedQA.PubMedQA import PubMedQA
from .MedMCQA.MedMCQA import MedMCQA
from .MedQA_USMLE.MedQA_USMLE import MedQA_USMLE
from .MMLU.MMLU import MMLU
from .MMLU_Pro.MMLU_Pro import MMLU_Pro
from .CMB.CMB import CMB
from .CMExam.CMExam import CMExam
from .MedQA_MCMLE.MedQA_MCMLE import MedQA_MCMLE
from .CMMLU.CMMLU import CMMLU
from .IU_XRAY.IU_XRAY import IU_XRAY
from .CheXpert_Plus.CheXpert_Plus import CheXpert_Plus
from .MIMIC_CXR.MIMIC_CXR import MIMIC_CXR
from .MedFrameQA.MedFrameQA import MedFrameQA
from .Medmnist.Medmnist import Medmnist
from .Amos.Amos import Amos
from .M3D.M3D import M3D
from .Rad3D.Rad3D import Rad3D
